<script src="assets/layout/js/jquery.min.js"></script>
  <script src="assets/layout/js/jquery-migrate-3.0.1.min.js"></script>
  <script src="assets/layout/js/popper.min.js"></script>
  <script src="assets/layout/js/bootstrap.min.js"></script>
  <script src="assets/layout/js/jquery.easing.1.3.js"></script>
  <script src="assets/layout/js/jquery.waypoints.min.js"></script>
  <script src="assets/layout/js/jquery.stellar.min.js"></script>
  <script src="assets/layout/js/owl.carousel.min.js"></script>
  <script src="assets/layout/js/jquery.magnific-popup.min.js"></script>
  <script src="assets/layout/js/aos.js"></script>
  <script src="assets/layout/js/jquery.animateNumber.min.js"></script>
  <script src="assets/layout/js/bootstrap-datepicker.js"></script>
  <script src="assets/layout/js/scrollax.min.js"></script>
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
  <script src="assets/layout/js/google-map.js"></script>
  <script src="assets/layout/js/main.js"></script>